# Generated by Django 3.0.4 on 2020-03-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=254)),
                ('usuario', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('correo', models.CharField(max_length=254)),
            ],
        ),
    ]
