# Generated by Django 3.0.4 on 2020-04-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
